#DataSource config
#############################################################################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/${DB_NAME}
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
#############################################################################

#LOG config
#############################################################################
# Define o nível mínimo global para o console
quarkus.log.console.level=INFO

# Define o nível padrão para as categorias (o padrão é INFO)
quarkus.log.level=DEBUG

# Se quiser ver os logs específicos do seu pacote/classe:
quarkus.log.category."org.seu.pacote".level=DEBUG
#############################################################################
